### ISSUE TITLE
RTL i18n break GNUSocial feeds

### ISSUE THREAD

**Issue by yair** [Toootim/Discussion#25]
![image](https://cloud.githubusercontent.com/assets/513922/25840957/af11c844-34a6-11e7-9002-a754aeecd1b7.png)

My ignorant guess is that &RLM or some other RTL hints are added to the status text at too early a stage (i.e. data that is federated), instead of later at the presentation stage, and for some reason, GNUSocial aligns the whole box according to it (i.e. including avatar).

Also, not sure if this is due to local experimentation or to stuff already in upstream and the issue should be reopened there.

**Comment by mitchellurgero** [comment]
What was odd for me is it even flipped the tagged user's names. But it might be a localization thing. It might be properly putting it in the timeline but IDK that for sure yet.

**Comment by ira-lb** [comment]
the RTL code I've been working on is all in the presentation stage (some of it even on the user's side in JS, not Ruby). I am pretty sure there are no Unicode RLM chars added to the posts, but that's not code I've gone over, I just know because I've ran recursive grep on the code and found no other places mentioning RTL or RLM. Surely, this could be a presentation issue on the GNUsocial side too...

**Comment by ira-lb** [comment]
> What was odd for me is it even flipped the tagged user's names.

That's the directionality. Perfectly expected. Mastodon has an open issue about ways to resolve that. I have a feeling it may not be in Mastodon 1.4, but probably 1.5. https://github.com/tootsuite/mastodon/issues/2350

(also, sorry for posting this from my work user, I'll switch back later)
